MTX-288
safely replace embedded file content to avoid minimize quotes jackson feature

diff --git a/hdf-to-yaml-converter/src/test/resources/yaml/IBMAIXDisk.yaml b/hdf-to-yaml-converter/src/test/resources/yaml/IBMAIXDisk.yaml
--- a/hdf-to-yaml-converter/src/test/resources/yaml/IBMAIXDisk.yaml
+++ b/hdf-to-yaml-converter/src/test/resources/yaml/IBMAIXDisk.yaml
@@ -1,9 +1,84 @@
 ---
 embedded:
-  EmbeddedFile(1): "#!/bin/sh\nfor DISK in `/usr/sbin/lsdev -C -c disk -F 'name'`\ndo\n\t/usr/sbin/lscfg -vp -l $DISK|/bin/tr \".\" \" \"|/usr/bin/awk -v diskId=$DISK 'BEGIN {\n\t\tmanufacturer = \"\";\n\t\tfruNumber = \"\";\n\t\tserialNumber = \"\";\n\t}\n\t/.*/ {\n\t\tif ($1 == \"Manufacturer\")\n\t\t{\n\t\t\tmanufacturer = $2;\n\t\t}\n\n\t\tif ($1 == \"FRU\" && $2 == \"Number\")\n\t\t{\n\t\t\tfruNumber = $3;\n\t\t}\n\n\t\tif ($1 == \"Serial\" && $2 == \"Number\")\n\t\t{\n\t\t\tserialNumber = $3;\n\t\t}\n\t}\n\tEND {\n\t\tprint \"MSHW;\" diskId \";\" manufacturer \";\" serialNumber \" (FRU: \" fruNumber \")\"\n\t}'\ndone"
-  EmbeddedFile(3): "#!/bin/sh\nLANG=C\nexport LANG\n\nERRORMESSAGE=`%{SUDO:/usr/bin/dd}/usr/bin/dd if=/dev/r$1 of=/dev/null count=20 2>&1`\nif /usr/bin/test \"$?\" = \"0\" ; then\n\tSTATUS=\"OK;Working\"\nelse\n\tSTATUS=`/usr/bin/echo $ERRORMESSAGE|/usr/bin/awk -F: '{\n\t\t\tif ($3 ~ /ermission/)\n\t\t\t{\n\t\t\t\tprint \"UNKNOWN;Insufficient privileges\"\n\t\t\t}\n\t\t\telse if ($3 ~ /o such file/)\n\t\t\t{\n\t\t\t\tprint \"UNKNOWN;\" $3\n\t\t\t}\n\t\t\telse\n\t\t\t{\n\t\t\t\tprint \"ALARM;\" $3\n\t\t\t}\n\t\t}'`\nfi\nTODAY=`/usr/bin/date +%m%d0000%y`\nERRORCOUNT=`/usr/bin/errpt -d H -s $TODAY -N $1|/usr/bin/tail -n +2|/usr/bin/wc -l|/usr/bin/awk '{print $1}'`\nif /usr/bin/test $ERRORCOUNT -gt 0 ; then\n\tLASTERROR=`/usr/bin/errpt -d H -s $TODAY -N $1|/usr/bin/head -n 2|/usr/bin/tail -n 1|/usr/bin/awk '{printf $1 \" (\"; for (i=6 ; i<NF ; i++) { printf $i \" \" } print $NF \")\"}'`\nfi\n/usr/bin/echo \"MSHW;$STATUS;$ERRORCOUNT;$LASTERROR\"\nexit\n\n"
-  EmbeddedFile(2): "#!/bin/sh\nfor DISK in `/usr/sbin/lsdev -C -c disk -F 'name'`\ndo\n\tSIZE=`/usr/sbin/lscfg -vp -l $DISK|/usr/bin/awk -F \"[() ]\" '/hdisk.*[0-9]+ MB)/ { print $(NF-2) }'`\n\t/bin/echo \"MSHW;$DISK;$SIZE\"\ndone"
-  EmbeddedFile(4): "#!/bin/sh\nLANG=C\nexport LANG\nTODAY=`/usr/bin/date +%m%d0000%y`\nERRORCOUNT=`/usr/bin/errpt -d H -s $TODAY -N $1|/usr/bin/tail -n +2|/usr/bin/wc -l|/usr/bin/awk '{print $1}'`\nif /usr/bin/test $ERRORCOUNT -gt 0 ; then\n\tLASTERROR=`/usr/bin/errpt -d H -s $TODAY -N $1|/usr/bin/head -n 2|/usr/bin/tail -n 1|/usr/bin/awk '{printf $1 \" (\"; for (i=6 ; i<NF ; i++) { printf $i \" \" } print $NF \")\"}'`\nfi\n/usr/bin/echo \"MSHW;$ERRORCOUNT;$LASTERROR\"\nexit"
+  EmbeddedFile(1): |-
+    #!/bin/sh
+    for DISK in `/usr/sbin/lsdev -C -c disk -F 'name'`
+    do
+        /usr/sbin/lscfg -vp -l $DISK|/bin/tr "." " "|/usr/bin/awk -v diskId=$DISK 'BEGIN {
+            manufacturer = "";
+            fruNumber = "";
+            serialNumber = "";
+        }
+        /.*/ {
+            if ($1 == "Manufacturer")
+            {
+                manufacturer = $2;
+            }
+
+            if ($1 == "FRU" && $2 == "Number")
+            {
+                fruNumber = $3;
+            }
+
+            if ($1 == "Serial" && $2 == "Number")
+            {
+                serialNumber = $3;
+            }
+        }
+        END {
+            print "MSHW;" diskId ";" manufacturer ";" serialNumber " (FRU: " fruNumber ")"
+        }'
+    done
+  EmbeddedFile(3): |+
+    #!/bin/sh
+    LANG=C
+    export LANG
+
+    ERRORMESSAGE=`%{SUDO:/usr/bin/dd}/usr/bin/dd if=/dev/r$1 of=/dev/null count=20 2>&1`
+    if /usr/bin/test "$?" = "0" ; then
+        STATUS="OK;Working"
+    else
+        STATUS=`/usr/bin/echo $ERRORMESSAGE|/usr/bin/awk -F: '{
+                if ($3 ~ /ermission/)
+                {
+                    print "UNKNOWN;Insufficient privileges"
+                }
+                else if ($3 ~ /o such file/)
+                {
+                    print "UNKNOWN;" $3
+                }
+                else
+                {
+                    print "ALARM;" $3
+                }
+            }'`
+    fi
+    TODAY=`/usr/bin/date +%m%d0000%y`
+    ERRORCOUNT=`/usr/bin/errpt -d H -s $TODAY -N $1|/usr/bin/tail -n +2|/usr/bin/wc -l|/usr/bin/awk '{print $1}'`
+    if /usr/bin/test $ERRORCOUNT -gt 0 ; then
+        LASTERROR=`/usr/bin/errpt -d H -s $TODAY -N $1|/usr/bin/head -n 2|/usr/bin/tail -n 1|/usr/bin/awk '{printf $1 " ("; for (i=6 ; i<NF ; i++) { printf $i " " } print $NF ")"}'`
+    fi
+    /usr/bin/echo "MSHW;$STATUS;$ERRORCOUNT;$LASTERROR"
+    exit
+
+  EmbeddedFile(2): |-
+    #!/bin/sh
+    for DISK in `/usr/sbin/lsdev -C -c disk -F 'name'`
+    do
+        SIZE=`/usr/sbin/lscfg -vp -l $DISK|/usr/bin/awk -F "[() ]" '/hdisk.*[0-9]+ MB)/ { print $(NF-2) }'`
+        /bin/echo "MSHW;$DISK;$SIZE"
+    done
+  EmbeddedFile(4): |-
+    #!/bin/sh
+    LANG=C
+    export LANG
+    TODAY=`/usr/bin/date +%m%d0000%y`
+    ERRORCOUNT=`/usr/bin/errpt -d H -s $TODAY -N $1|/usr/bin/tail -n +2|/usr/bin/wc -l|/usr/bin/awk '{print $1}'`
+    if /usr/bin/test $ERRORCOUNT -gt 0 ; then
+        LASTERROR=`/usr/bin/errpt -d H -s $TODAY -N $1|/usr/bin/head -n 2|/usr/bin/tail -n 1|/usr/bin/awk '{printf $1 " ("; for (i=6 ; i<NF ; i++) { printf $i " " } print $NF ")"}'`
+    fi
+    /usr/bin/echo "MSHW;$ERRORCOUNT;$LASTERROR"
+    exit
 translations:
   ErrorcounttoStatusTranslationTable:
     "0": ok
diff --git a/hdf-to-yaml-converter/src/test/resources/yaml/SmartMonLinux.yaml b/hdf-to-yaml-converter/src/test/resources/yaml/SmartMonLinux.yaml
--- a/hdf-to-yaml-converter/src/test/resources/yaml/SmartMonLinux.yaml
+++ b/hdf-to-yaml-converter/src/test/resources/yaml/SmartMonLinux.yaml
@@ -1,10 +1,151 @@
 ---
 embedded:
-  EmbeddedFile(1): "#!/bin/sh\nSMARTD=$1\nSMARTCTL=$2\nTMPFILE=/tmp/MS_HW_smartmontoolsHDF_$$\n\n$SMARTD -c>$TMPFILE\n$SMARTD -q onecheck>>$TMPFILE\n\nDISKIDLIST=`cat $TMPFILE|awk '/^Device: .* is SMART capable/ {\n\tdeviceID = $2;\n\tif (substr(deviceID, length(deviceID), 1) == \",\")\n\t{\n\t\tdeviceID = substr(deviceID, 1, length(deviceID)-1);\n\t}\n\tprint deviceID\n}'`\n\n/bin/rm -f $TMPFILE\n\nfor DISKID in $DISKIDLIST\ndo\n\t$SMARTCTL -a $DISKID|awk -v deviceID=$DISKID 'BEGIN {\n\t\tvendor = \"\";\n\t\tserialNumber = \"\";\n\t}\n\t{\n\t\tif ($1 == \"Device:\")\n\t\t{\n\t\t\tif ($5 == \"Version:\") { vendor = $2 \" \" $3 \" \" $4; }\n\t\t\telse if ($4 == \"Version:\") { vendor = $2 \" \" $3; }\n\t\t\telse { vendor = $2; }\n\t\t}\n\n\t\tif ($1 == \"Device\" && $2 == \"Model:\")\n\t\t{\n\t\t\tvendor = $3;\n\t\t}\n\n\t\tif ($0 ~ /^Serial [Nn]umber: /)\n\t\t{\n\t\t\tserialNumber = $3;\n\t\t}\n\t}\n\tEND {\n\t\tprint \"MSHW;\" deviceID \";\" vendor \";\" serialNumber\n\t}'\ndone"
-  EmbeddedFile(3): "{\n\tif ($0 ~ /Current Drive Temperature: *[0-9]* C$/)\n\t{\n\t\tprint \"MSHW;\" $4\n\t\texit;\n\t}\n\n\tif ($1 == \"194\" && $10 ~ /[0-9]+/)\n\t{\n\t  print \"MSHW;\" $10\n\t  exit;\n\t}\n}"
-  EmbeddedFile(2): "#!/bin/sh\nSMARTD=$1\nSMARTCTL=$2\nTMPFILE=/tmp/MS_HW_smartmontoolsHDF_$$\n\n$SMARTD -c>$TMPFILE\n$SMARTD -q onecheck>>$TMPFILE\n\nDISKIDLIST=`cat $TMPFILE|awk '/^Device: .* is SMART capable/ {\n\tdeviceID = $2;\n\tif (substr(deviceID, length(deviceID), 1) == \",\")\n\t{\n\t\tdeviceID = substr(deviceID, 1, length(deviceID)-1);\n\t}\n\tprint deviceID\n}'`\n\n/bin/rm -f $TMPFILE\n\nfor DISKID in $DISKIDLIST\ndo\n\t$SMARTCTL -a $DISKID|awk -v deviceID=$DISKID 'BEGIN {\n\t\tfoundTemperature = 0;\n\t\twarningThreshold = \"\";\n\t}\n\t{\n\t\tif ($0 ~ /^Current Drive Temperature: *[0-9]* C$/)\n\t\t{\n\t\t\tfoundTemperature = 1;\n\t\t}\n\n\t\tif ($1 == \"194\" && $10 ~ /[0-9]+/)\n\t\t{\n\t\t  foundTemperature = 1;\n\t\t  warningThreshold = 53;\n\t\t}\n\n\t\tif ($0 ~ /^Drive Trip Temperature: /)\n\t\t{\n\t\t\twarningThreshold = $4;\n\t\t}\n\t}\n\tEND {\n\t\tif (foundTemperature == 1)\n\t\t{\n\t\t\tprint \"MSHW;\" deviceID \";\" warningThreshold\n\t\t}\n\t}'\ndone"
-  EmbeddedFile(5): "#!/bin/sh\nERRORMESSAGE=`%{SUDO:/bin/dd}/bin/dd if=$1 of=/dev/null count=20 2>&1`\nif [ \"$?\" = \"0\" ]; then\n\t/bin/echo \"MSHW;1;OK;Working\";\nelse\n\tERRORMESSAGE=`/bin/echo $ERRORMESSAGE|/bin/awk -F: '($4 !~ /denied/ && $4 !~ /[Nn]o such file/) {print $4}'`\n\tif [ -z \"$ERRORMESSAGE\" ]; then\n\t\t/bin/echo \"MSHW;1;UNKNOWN;Unknown Status\";\n\telse\n\t\t/bin/echo \"MSHW;1;ALARM;$ERRORMESSAGE\";\n\tfi\nfi"
-  EmbeddedFile(4): "{\n\tif ($0 ~ /^SMART Sense: /)\n\t{\n\t\tprint \"MSHW;\" $3\n\t\texit;\n\t}\n\n\tif ($0 ~ /^SMART Health Status: /)\n\t{\n\t\tprint \"MSHW;\" $4\n\t\texit;\n\t}\n\n\tif ($0 ~ /^SMART overall-health self-assessment test result: /)\n\t{\n\t\tprint \"MSHW;\" $6\n\t\texit;\n\t}\n\n}"
+  EmbeddedFile(1): |-
+    #!/bin/sh
+    SMARTD=$1
+    SMARTCTL=$2
+    TMPFILE=/tmp/MS_HW_smartmontoolsHDF_$$
+
+    $SMARTD -c>$TMPFILE
+    $SMARTD -q onecheck>>$TMPFILE
+
+    DISKIDLIST=`cat $TMPFILE|awk '/^Device: .* is SMART capable/ {
+        deviceID = $2;
+        if (substr(deviceID, length(deviceID), 1) == ",")
+        {
+            deviceID = substr(deviceID, 1, length(deviceID)-1);
+        }
+        print deviceID
+    }'`
+
+    /bin/rm -f $TMPFILE
+
+    for DISKID in $DISKIDLIST
+    do
+        $SMARTCTL -a $DISKID|awk -v deviceID=$DISKID 'BEGIN {
+            vendor = "";
+            serialNumber = "";
+        }
+        {
+            if ($1 == "Device:")
+            {
+                if ($5 == "Version:") { vendor = $2 " " $3 " " $4; }
+                else if ($4 == "Version:") { vendor = $2 " " $3; }
+                else { vendor = $2; }
+            }
+
+            if ($1 == "Device" && $2 == "Model:")
+            {
+                vendor = $3;
+            }
+
+            if ($0 ~ /^Serial [Nn]umber: /)
+            {
+                serialNumber = $3;
+            }
+        }
+        END {
+            print "MSHW;" deviceID ";" vendor ";" serialNumber
+        }'
+    done
+  EmbeddedFile(3): |-
+    {
+        if ($0 ~ /Current Drive Temperature: *[0-9]* C$/)
+        {
+            print "MSHW;" $4
+            exit;
+        }
+
+        if ($1 == "194" && $10 ~ /[0-9]+/)
+        {
+          print "MSHW;" $10
+          exit;
+        }
+    }
+  EmbeddedFile(2): |-
+    #!/bin/sh
+    SMARTD=$1
+    SMARTCTL=$2
+    TMPFILE=/tmp/MS_HW_smartmontoolsHDF_$$
+
+    $SMARTD -c>$TMPFILE
+    $SMARTD -q onecheck>>$TMPFILE
+
+    DISKIDLIST=`cat $TMPFILE|awk '/^Device: .* is SMART capable/ {
+        deviceID = $2;
+        if (substr(deviceID, length(deviceID), 1) == ",")
+        {
+            deviceID = substr(deviceID, 1, length(deviceID)-1);
+        }
+        print deviceID
+    }'`
+
+    /bin/rm -f $TMPFILE
+
+    for DISKID in $DISKIDLIST
+    do
+        $SMARTCTL -a $DISKID|awk -v deviceID=$DISKID 'BEGIN {
+            foundTemperature = 0;
+            warningThreshold = "";
+        }
+        {
+            if ($0 ~ /^Current Drive Temperature: *[0-9]* C$/)
+            {
+                foundTemperature = 1;
+            }
+
+            if ($1 == "194" && $10 ~ /[0-9]+/)
+            {
+              foundTemperature = 1;
+              warningThreshold = 53;
+            }
+
+            if ($0 ~ /^Drive Trip Temperature: /)
+            {
+                warningThreshold = $4;
+            }
+        }
+        END {
+            if (foundTemperature == 1)
+            {
+                print "MSHW;" deviceID ";" warningThreshold
+            }
+        }'
+    done
+  EmbeddedFile(5): |-
+    #!/bin/sh
+    ERRORMESSAGE=`%{SUDO:/bin/dd}/bin/dd if=$1 of=/dev/null count=20 2>&1`
+    if [ "$?" = "0" ]; then
+        /bin/echo "MSHW;1;OK;Working";
+    else
+        ERRORMESSAGE=`/bin/echo $ERRORMESSAGE|/bin/awk -F: '($4 !~ /denied/ && $4 !~ /[Nn]o such file/) {print $4}'`
+        if [ -z "$ERRORMESSAGE" ]; then
+            /bin/echo "MSHW;1;UNKNOWN;Unknown Status";
+        else
+            /bin/echo "MSHW;1;ALARM;$ERRORMESSAGE";
+        fi
+    fi
+  EmbeddedFile(4): |-
+    {
+        if ($0 ~ /^SMART Sense: /)
+        {
+            print "MSHW;" $3
+            exit;
+        }
+
+        if ($0 ~ /^SMART Health Status: /)
+        {
+            print "MSHW;" $4
+            exit;
+        }
+
+        if ($0 ~ /^SMART overall-health self-assessment test result: /)
+        {
+            print "MSHW;" $6
+            exit;
+        }
+
+    }
 translations:
   PhysicalDiskPredictedFailureTranslationTable:
     default: 1;true
diff --git a/hdf-to-yaml-converter/src/test/resources/yaml/SunIostat.yaml b/hdf-to-yaml-converter/src/test/resources/yaml/SunIostat.yaml
--- a/hdf-to-yaml-converter/src/test/resources/yaml/SunIostat.yaml
+++ b/hdf-to-yaml-converter/src/test/resources/yaml/SunIostat.yaml
@@ -1,9 +1,366 @@
 ---
 embedded:
-  EmbeddedFile(1): "{\n\tif ($0 ~ /^c[0-9]+t[0-9A-Z]+d[0-9]+/ || $0 ~ /^s+d[0-9]+/)\n\t{\n\t\tif ($1 ~ /^c[0-9]+t[0-9A-Z]+d[0-9]+/)\n\t\t{\n\t\t\ttargetIndex = index($1, \"t\")\n\t\t\tcontroller = substr($1, 1, targetIndex - 1)\n\t\t}\n\t\telse\n\t\t{\n\t\t\tcontroller = \"Other\"\n\t\t}\n\t}\n\n\tif ($0 ~/Illegal Request:/)\n\t{\n\t\tprint \"MSHW;\" controller\n\t}\n}"
-  EmbeddedFile(3): "{\n\tif ($0 ~ /^c[0-9]+t[0-9A-Z]+d[0-9]+/ || $0 ~ /^s+d[0-9]+/)\n\t{\n\t\tdisk = $1\n\t\tproduct = \"\"\n\t\ttransporterror = 0\n\t\thardwareerror = 0\n\t\tmediaerror = 0\n\t\tdevicenotready = 0\n\t\tnodevice = 0\n\t\trecoverable = 0\n\t\tillegalrequests = 0\n\t\tpredictivefailureanalysis = 0\n\t\tstatusinformation = \"\"\n\t\ttotalerror = 0\n\t\tvendor = \"\"\n\t\tsize = 0\n\t}\n\n\tif ($0 ~ /Product: /)\n\t{\n\t\tindex1 = index($0, \"Product: \" ) + length(\"Product: \")\n\t\tproduct = substr($0, index1, length-index1)\n\t\tindex1 = index(product, \":\")\n\t\tif (index1 > 0)\n\t\t{\n\t\t\tproduct = substr(product, 1, index1-1)\n\t\t\tn = split(product, a, \" \")\n\t\t\tproduct = \"\"\n\t\t\tfor (i=1 ; i<n ; i++)\n\t\t\t{\n\t\t\t\tproduct = product a[i]\n\t\t\t\tif (i < n-1)\n\t\t\t\t\tproduct = product \" \"\n\t\t\t}\n\t\t}\n\t}\n\tif ($0 ~ /Size: /)\n\t{\n\t\tindex1 = index($0, \"<\") + 1\n\t\tindex2 = index($0, \" bytes>\")\n\t\tsize = substr($0, index1, index2-index1)\n\t}\n\n\tif ($8 == \"Transport\" && ($9 == \"Errors:\" || $9 == \"errors:\"))\n\t{\n\t\ttransporterror = $10\n\t}\n\n\tif ($5 == \"Hard\" && ($6 == \"Errors:\" || $6 == \"errors:\"))\n\t{\n\t\thardwareerror = $7\n\t}\n\n\tif ($1 == \"Media\" && ($2 == \"Error:\" || $2 == \"error:\"))\n\t{\n\t\tmediaerror = $3\n\t}\n\n\tif ($4 == \"Device\" && $5 == \"Not\" && $6 == \"Ready:\")\n\t{\n\t\tdevicenotready = $7\n\t}\n\n\tif ($8 == \"No\" && $9 == \"Device:\")\n\t{\n\t\tnodevice = $10\n\t}\n\n\tif ($11 == \"Recoverable:\")\n\t{\n\t\trecoverable = $12\n\t}\n\n\tif ($1 == \"Illegal\" && $2 == \"Request:\")\n\t{\n\t\tillegalrequests = $3\n\t}\n\n\tif ($4 == \"Predictive\" && $5 == \"Failure\" && $6 == \"Analysis:\")\n\t{\n\t\tpredictivefailureanalysis = $7\n\t}\n\n\tif ($0 ~/Illegal Request:/)\n\t{\n\t\thardwareerror = hardwareerror - mediaerror - devicenotready - nodevice\n\t\tif (hardwareerror < 0)\n\t\t{\n\t\t\thardwareerror = 0\n\t\t}\n\n\t\tif (predictivefailureanalysis > 0)\n\t\t{\n\t\t\tpredictivefailureanalysis = \"TRUE\"\n\t\t}\n\t\telse\n\t\t{\n\t\t\tpredictivefailureanalysis = \"FALSE\"\n\t\t}\n\n\t\ttotalerror = recoverable + transporterror + mediaerror + devicenotready + nodevice + hardwareerror\n\n\t\tif (disk != \"\" && product ~ /SUN[0-9\\.]+[GT]/ && size > 10)\n\t\t{\n\t\t\tprint \"MSHW;\" disk \";\" totalerror \";\" hardwareerror \";\" mediaerror \";\" devicenotready \";\" nodevice \";\" transporterror \";\" recoverable \";\" illegalrequests \";\" predictivefailureanalysis\n\t\t}\n\n\t\tproduct = \"\"\n\t\ttransporterror = 0\n\t\thardwareerror = 0\n\t\tmediaerror = 0\n\t\tdevicenotready = 0\n\t\tnodevice = 0\n\t\trecoverable = 0\n\t\tillegalrequests = 0\n\t\tpredictivefailureanalysis = 0\n\t\tstatusinformation = \"\"\n\t\ttotalerror = 0\n\t\tvendor = \"\"\n\t\tsize = 0\n\n\t}\n\n}"
-  EmbeddedFile(2): "{\n\tif ($0 ~ /^c[0-9]+t[0-9A-Z]+d[0-9]+/ || $0 ~ /^s+d[0-9]+/)\n\t{\n\t\tdisk = $1\n\t\tsize = \"0\"\n\t\tvendor = \"\"\n\t\tproduct = \"\"\n\t\tmodel = \"\"\n\t\tproductmodel = \"\"\n\t\tserial = \"\"\n\t\tif (disk ~ /^c[0-9]+t[0-9A-Z]+d[0-9]+/)\n\t\t{\n\t\t\ttargetIndex = index(disk, \"t\")\n\t\t\tcontroller = substr(disk, 1, targetIndex - 1)\n\t\t}\n\t\telse\n\t\t{\n\t\t\tcontroller = \"Other\"\n\t\t}\n\t}\n\n\tif ($0 ~ /Size: /)\n\t{\n\t\tindex1 = index($0, \"<\") + 1\n\t\tindex2 = index($0, \" bytes>\")\n\t\tsize = substr($0, index1, index2-index1)\n\t}\n\n\tif ($0 ~ /Vendor: /)\n\t{\n\t\tindex1 = index($0, \"Vendor: \" ) + length(\"Vendor: \")\n\t\tvendor = substr($0, index1, length-index1)\n\t\tindex1 = index(vendor, \":\")\n\t\tif (index1 > 0)\n\t\t{\n\t\t\tvendor = substr(vendor, 1, index1-1)\n\t\t\tn = split(vendor, a, \" \")\n\t\t\tvendor = \"\"\n\t\t\tfor (i=1 ; i<n ; i++)\n\t\t\t{\n\t\t\t\tvendor = vendor a[i]\n\t\t\t\tif (i < n-1)\n\t\t\t\t\tvendor = vendor \" \"\n\t\t\t}\n\t\t}\n\t}\n\n\tif ($0 ~ /Model: /)\n\t{\n\t\tindex1 = index($0, \"Model: \" ) + length(\"Model: \")\n\t\tmodel = substr($0, index1, length-index1)\n\t\tindex1 = index(model, \":\")\n\t\tif (index1 > 0)\n\t\t{\n\t\t\tmodel = substr(model, 1, index1-1)\n\t\t\tn = split(model, a, \" \")\n\t\t\tmodel = \"\"\n\t\t\tfor (i=1 ; i<n ; i++)\n\t\t\t{\n\t\t\t\tmodel = model a[i]\n\t\t\t\tif (i < n-1)\n\t\t\t\t\tmodel = model \" \"\n\t\t\t}\n\t\t}\n\t}\n\n\tif ($0 ~ /Product: /)\n\t{\n\t\tindex1 = index($0, \"Product: \" ) + length(\"Product: \")\n\t\tproduct = substr($0, index1, length-index1)\n\t\tindex1 = index(product, \":\")\n\t\tif (index1 > 0)\n\t\t{\n\t\t\tproduct = substr(product, 1, index1-1)\n\t\t\tn = split(product, a, \" \")\n\t\t\tproduct = \"\"\n\t\t\tfor (i=1 ; i<n ; i++)\n\t\t\t{\n\t\t\t\tproduct = product a[i]\n\t\t\t\tif (i < n-1)\n\t\t\t\t\tproduct = product \" \"\n\t\t\t}\n\t\t}\n\t}\n\n\tif ($0 ~ /Serial No: /)\n\t{\n\t\tindex1 = index($0, \"Serial No: \" ) + length(\"Serial No: \")\n\t\tserial = substr($0, index1, length-index1)\n\t\tindex1 = index(serial, \":\")\n\t\tif (index1 > 0)\n\t\t{\n\t\t\tserial = substr(serial, 1, index1-1)\n\t\t\tn = split(serial, a, \" \")\n\t\t\tserial = \"\"\n\t\t\tfor (i=1 ; i<n ; i++)\n\t\t\t{\n\t\t\t\tserial = serial a[i]\n\t\t\t\tif (i < n-1)\n\t\t\t\t\tserial = serial \" \"\n\t\t\t}\n\t\t}\n\n\t}\n\n\tif ($0 ~/Illegal Request:/)\n\t{\n\t\tif (product != \"\" && model != \"\")\n\t\t{\n\t\t\tproductmodel = product \" \" model\n\t\t}\n\t\telse\n\t\t{\n\t\t\tproductmodel = product model\n\t\t}\n\n\t\tif (disk != \"\" && product ~ /SUN[0-9\\.]+[GT]/ && size > 10)\n\t\t{\n\t\t\tprint \"MSHW;\" disk \";\" controller \";\" size \";\" vendor \" \" productmodel \";\" serial\n\t\t}\n\n\t\tdisk = \"\"\n\t\tsize = \"0\"\n\t\tvendor = \"\"\n\t\tproduct = \"\"\n\t\tmodel = \"\"\n\t\tproductmodel = \"\"\n\t\tserial = \"\"\n\n\t}\n\n}"
-  EmbeddedFile(4): "DISKLIST=`/usr/bin/iostat -En|/usr/bin/awk '{\n\tif ($0 ~ /^c[0-9]+t[0-9A-Z]+d[0-9]+/ || $0 ~ /^s+d[0-9]+/)\n\t{\n\t\tdisk = $1\n\t\tproduct = \"\"\n\t}\n\n\tif ($0 ~ /Product: /)\n\t{\n\t\tindex1 = index($0, \"Product: \" ) + length(\"Product: \")\n\t\tproduct = substr($0, index1, length-index1)\n\t\tindex1 = index(product, \":\")\n\t\tif (index1 > 0)\n\t\t{\n\t\t\tproduct = substr(product, 1, index1-1)\n\t\t\tn = split(product, a, \" \")\n\t\t\tproduct = \"\"\n\t\t\tfor (i=1 ; i<n ; i++)\n\t\t\t{\n\t\t\t\tproduct = product a[i]\n\t\t\t\tif (i < n-1)\n\t\t\t\t\tproduct = product \" \"\n\t\t\t}\n\t\t}\n\t}\n\tif ($0 ~ /Size: /)\n\t{\n\t\tindex1 = index($0, \"<\") + 1\n\t\tindex2 = index($0, \" bytes>\")\n\t\tsize = substr($0, index1, index2-index1)\n\t}\n\tif ($0 ~/Illegal Request:/)\n\t{\n\t\tif (disk != \"\" && product ~ /SUN[0-9\\.]+[GT]/ && size > 10)\n\t\t{\n\t\t\tprint disk\n\t\t}\n\n\t\tdisk = \"\"\n\t\tproduct = \"\"\n\t}\n}'|/usr/bin/head -30`\n\nLANG=C\nexport LANG\n\nfor DISK in $DISKLIST\ndo\n\n\tif /usr/bin/echo $DISK|/usr/bin/grep \"^c[0-9][0-9]*t[0-9A-Z][0-9A-Z]*d[0-9][0-9]*\" 2>/dev/null >/dev/null; then\n\t\tCTDSLIST=`/usr/bin/ls /dev/rdsk/$DISK\"s\"* 2>/dev/null`\n\telse\n\t\tDRIVERNAME=`/usr/bin/echo $DISK|/usr/bin/tr -d [:digit:]`\n\t\tINSTANCENUMBER=`/usr/bin/echo $DISK|/usr/bin/tr -d [:alpha:]`\n\t\tDEVICEPATH=`/usr/xpg4/bin/awk -v instanceNumber=$INSTANCENUMBER -v driverName=$DRIVERNAME '($(NF-1) == instanceNumber) && ($NF == \"\\\"\"driverName\"\\\"\") { print $1 }' /etc/path_to_inst|/usr/bin/tr -d \\\"`\n\t\tCTDSLIST=`/usr/bin/ls -l /dev/rdsk/c*|/usr/xpg4/bin/awk -v devicePath=\"$DEVICEPATH\" '($NF ~ devicePath && devicePath != \"\") { print $(NF-2); }'`\n\tfi\n\n\tif /usr/bin/test -z \"$CTDSLIST\" ; then\n\t\t/usr/bin/echo \"MSHW;$DISK;UNKNOWN;Couldn't find corresponding block device\";\n\telse\n\t\tFOUNDWORKINGCTDS=0\n\t\tfor CTDS in $CTDSLIST\n\t\tdo\n\t\t\tERRORMESSAGE=`%{SUDO:/usr/bin/dd}/usr/bin/dd if=$CTDS of=/dev/null count=20 2>&1`\n\t\t\tif /usr/bin/test \"$?\" = \"0\" ; then\n\t\t\t\t/usr/bin/echo \"MSHW;$DISK;OK;Working\"\n\t\t\t\tFOUNDWORKINGCTDS=1\n\t\t\t\tbreak\n\t\t\tfi\n\t\tdone\n\t\tif /usr/bin/test \"$FOUNDWORKINGCTDS\" == \"0\" ; then\n\t\t\tERRORMESSAGE=`/usr/bin/echo $ERRORMESSAGE|/usr/bin/awk -F: '($4 !~ /denied/ && $4 !~ /[Nn]o such file/) {print $4}'`\n\t\t\tif /usr/bin/test -z \"$ERRORMESSAGE\" ; then\n\t\t\t\t/usr/bin/echo \"MSHW;$DISK;UNKNOWN;Unknown Status\";\n\t\t\telse\n\t\t\t\t/usr/bin/echo \"MSHW;$DISK;ALARM;$ERRORMESSAGE\";\n\t\t\tfi\n\t\tfi\n\tfi\ndone"
+  EmbeddedFile(1): |-
+    {
+        if ($0 ~ /^c[0-9]+t[0-9A-Z]+d[0-9]+/ || $0 ~ /^s+d[0-9]+/)
+        {
+            if ($1 ~ /^c[0-9]+t[0-9A-Z]+d[0-9]+/)
+            {
+                targetIndex = index($1, "t")
+                controller = substr($1, 1, targetIndex - 1)
+            }
+            else
+            {
+                controller = "Other"
+            }
+        }
+
+        if ($0 ~/Illegal Request:/)
+        {
+            print "MSHW;" controller
+        }
+    }
+  EmbeddedFile(3): |-
+    {
+        if ($0 ~ /^c[0-9]+t[0-9A-Z]+d[0-9]+/ || $0 ~ /^s+d[0-9]+/)
+        {
+            disk = $1
+            product = ""
+            transporterror = 0
+            hardwareerror = 0
+            mediaerror = 0
+            devicenotready = 0
+            nodevice = 0
+            recoverable = 0
+            illegalrequests = 0
+            predictivefailureanalysis = 0
+            statusinformation = ""
+            totalerror = 0
+            vendor = ""
+            size = 0
+        }
+
+        if ($0 ~ /Product: /)
+        {
+            index1 = index($0, "Product: " ) + length("Product: ")
+            product = substr($0, index1, length-index1)
+            index1 = index(product, ":")
+            if (index1 > 0)
+            {
+                product = substr(product, 1, index1-1)
+                n = split(product, a, " ")
+                product = ""
+                for (i=1 ; i<n ; i++)
+                {
+                    product = product a[i]
+                    if (i < n-1)
+                        product = product " "
+                }
+            }
+        }
+        if ($0 ~ /Size: /)
+        {
+            index1 = index($0, "<") + 1
+            index2 = index($0, " bytes>")
+            size = substr($0, index1, index2-index1)
+        }
+
+        if ($8 == "Transport" && ($9 == "Errors:" || $9 == "errors:"))
+        {
+            transporterror = $10
+        }
+
+        if ($5 == "Hard" && ($6 == "Errors:" || $6 == "errors:"))
+        {
+            hardwareerror = $7
+        }
+
+        if ($1 == "Media" && ($2 == "Error:" || $2 == "error:"))
+        {
+            mediaerror = $3
+        }
+
+        if ($4 == "Device" && $5 == "Not" && $6 == "Ready:")
+        {
+            devicenotready = $7
+        }
+
+        if ($8 == "No" && $9 == "Device:")
+        {
+            nodevice = $10
+        }
+
+        if ($11 == "Recoverable:")
+        {
+            recoverable = $12
+        }
+
+        if ($1 == "Illegal" && $2 == "Request:")
+        {
+            illegalrequests = $3
+        }
+
+        if ($4 == "Predictive" && $5 == "Failure" && $6 == "Analysis:")
+        {
+            predictivefailureanalysis = $7
+        }
+
+        if ($0 ~/Illegal Request:/)
+        {
+            hardwareerror = hardwareerror - mediaerror - devicenotready - nodevice
+            if (hardwareerror < 0)
+            {
+                hardwareerror = 0
+            }
+
+            if (predictivefailureanalysis > 0)
+            {
+                predictivefailureanalysis = "TRUE"
+            }
+            else
+            {
+                predictivefailureanalysis = "FALSE"
+            }
+
+            totalerror = recoverable + transporterror + mediaerror + devicenotready + nodevice + hardwareerror
+
+            if (disk != "" && product ~ /SUN[0-9\.]+[GT]/ && size > 10)
+            {
+                print "MSHW;" disk ";" totalerror ";" hardwareerror ";" mediaerror ";" devicenotready ";" nodevice ";" transporterror ";" recoverable ";" illegalrequests ";" predictivefailureanalysis
+            }
+
+            product = ""
+            transporterror = 0
+            hardwareerror = 0
+            mediaerror = 0
+            devicenotready = 0
+            nodevice = 0
+            recoverable = 0
+            illegalrequests = 0
+            predictivefailureanalysis = 0
+            statusinformation = ""
+            totalerror = 0
+            vendor = ""
+            size = 0
+
+        }
+
+    }
+  EmbeddedFile(2): |-
+    {
+        if ($0 ~ /^c[0-9]+t[0-9A-Z]+d[0-9]+/ || $0 ~ /^s+d[0-9]+/)
+        {
+            disk = $1
+            size = "0"
+            vendor = ""
+            product = ""
+            model = ""
+            productmodel = ""
+            serial = ""
+            if (disk ~ /^c[0-9]+t[0-9A-Z]+d[0-9]+/)
+            {
+                targetIndex = index(disk, "t")
+                controller = substr(disk, 1, targetIndex - 1)
+            }
+            else
+            {
+                controller = "Other"
+            }
+        }
+
+        if ($0 ~ /Size: /)
+        {
+            index1 = index($0, "<") + 1
+            index2 = index($0, " bytes>")
+            size = substr($0, index1, index2-index1)
+        }
+
+        if ($0 ~ /Vendor: /)
+        {
+            index1 = index($0, "Vendor: " ) + length("Vendor: ")
+            vendor = substr($0, index1, length-index1)
+            index1 = index(vendor, ":")
+            if (index1 > 0)
+            {
+                vendor = substr(vendor, 1, index1-1)
+                n = split(vendor, a, " ")
+                vendor = ""
+                for (i=1 ; i<n ; i++)
+                {
+                    vendor = vendor a[i]
+                    if (i < n-1)
+                        vendor = vendor " "
+                }
+            }
+        }
+
+        if ($0 ~ /Model: /)
+        {
+            index1 = index($0, "Model: " ) + length("Model: ")
+            model = substr($0, index1, length-index1)
+            index1 = index(model, ":")
+            if (index1 > 0)
+            {
+                model = substr(model, 1, index1-1)
+                n = split(model, a, " ")
+                model = ""
+                for (i=1 ; i<n ; i++)
+                {
+                    model = model a[i]
+                    if (i < n-1)
+                        model = model " "
+                }
+            }
+        }
+
+        if ($0 ~ /Product: /)
+        {
+            index1 = index($0, "Product: " ) + length("Product: ")
+            product = substr($0, index1, length-index1)
+            index1 = index(product, ":")
+            if (index1 > 0)
+            {
+                product = substr(product, 1, index1-1)
+                n = split(product, a, " ")
+                product = ""
+                for (i=1 ; i<n ; i++)
+                {
+                    product = product a[i]
+                    if (i < n-1)
+                        product = product " "
+                }
+            }
+        }
+
+        if ($0 ~ /Serial No: /)
+        {
+            index1 = index($0, "Serial No: " ) + length("Serial No: ")
+            serial = substr($0, index1, length-index1)
+            index1 = index(serial, ":")
+            if (index1 > 0)
+            {
+                serial = substr(serial, 1, index1-1)
+                n = split(serial, a, " ")
+                serial = ""
+                for (i=1 ; i<n ; i++)
+                {
+                    serial = serial a[i]
+                    if (i < n-1)
+                        serial = serial " "
+                }
+            }
+
+        }
+
+        if ($0 ~/Illegal Request:/)
+        {
+            if (product != "" && model != "")
+            {
+                productmodel = product " " model
+            }
+            else
+            {
+                productmodel = product model
+            }
+
+            if (disk != "" && product ~ /SUN[0-9\.]+[GT]/ && size > 10)
+            {
+                print "MSHW;" disk ";" controller ";" size ";" vendor " " productmodel ";" serial
+            }
+
+            disk = ""
+            size = "0"
+            vendor = ""
+            product = ""
+            model = ""
+            productmodel = ""
+            serial = ""
+
+        }
+
+    }
+  EmbeddedFile(4): |-
+    DISKLIST=`/usr/bin/iostat -En|/usr/bin/awk '{
+        if ($0 ~ /^c[0-9]+t[0-9A-Z]+d[0-9]+/ || $0 ~ /^s+d[0-9]+/)
+        {
+            disk = $1
+            product = ""
+        }
+
+        if ($0 ~ /Product: /)
+        {
+            index1 = index($0, "Product: " ) + length("Product: ")
+            product = substr($0, index1, length-index1)
+            index1 = index(product, ":")
+            if (index1 > 0)
+            {
+                product = substr(product, 1, index1-1)
+                n = split(product, a, " ")
+                product = ""
+                for (i=1 ; i<n ; i++)
+                {
+                    product = product a[i]
+                    if (i < n-1)
+                        product = product " "
+                }
+            }
+        }
+        if ($0 ~ /Size: /)
+        {
+            index1 = index($0, "<") + 1
+            index2 = index($0, " bytes>")
+            size = substr($0, index1, index2-index1)
+        }
+        if ($0 ~/Illegal Request:/)
+        {
+            if (disk != "" && product ~ /SUN[0-9\.]+[GT]/ && size > 10)
+            {
+                print disk
+            }
+
+            disk = ""
+            product = ""
+        }
+    }'|/usr/bin/head -30`
+
+    LANG=C
+    export LANG
+
+    for DISK in $DISKLIST
+    do
+
+        if /usr/bin/echo $DISK|/usr/bin/grep "^c[0-9][0-9]*t[0-9A-Z][0-9A-Z]*d[0-9][0-9]*" 2>/dev/null >/dev/null; then
+            CTDSLIST=`/usr/bin/ls /dev/rdsk/$DISK"s"* 2>/dev/null`
+        else
+            DRIVERNAME=`/usr/bin/echo $DISK|/usr/bin/tr -d [:digit:]`
+            INSTANCENUMBER=`/usr/bin/echo $DISK|/usr/bin/tr -d [:alpha:]`
+            DEVICEPATH=`/usr/xpg4/bin/awk -v instanceNumber=$INSTANCENUMBER -v driverName=$DRIVERNAME '($(NF-1) == instanceNumber) && ($NF == "\""driverName"\"") { print $1 }' /etc/path_to_inst|/usr/bin/tr -d \"`
+            CTDSLIST=`/usr/bin/ls -l /dev/rdsk/c*|/usr/xpg4/bin/awk -v devicePath="$DEVICEPATH" '($NF ~ devicePath && devicePath != "") { print $(NF-2); }'`
+        fi
+
+        if /usr/bin/test -z "$CTDSLIST" ; then
+            /usr/bin/echo "MSHW;$DISK;UNKNOWN;Couldn't find corresponding block device";
+        else
+            FOUNDWORKINGCTDS=0
+            for CTDS in $CTDSLIST
+            do
+                ERRORMESSAGE=`%{SUDO:/usr/bin/dd}/usr/bin/dd if=$CTDS of=/dev/null count=20 2>&1`
+                if /usr/bin/test "$?" = "0" ; then
+                    /usr/bin/echo "MSHW;$DISK;OK;Working"
+                    FOUNDWORKINGCTDS=1
+                    break
+                fi
+            done
+            if /usr/bin/test "$FOUNDWORKINGCTDS" == "0" ; then
+                ERRORMESSAGE=`/usr/bin/echo $ERRORMESSAGE|/usr/bin/awk -F: '($4 !~ /denied/ && $4 !~ /[Nn]o such file/) {print $4}'`
+                if /usr/bin/test -z "$ERRORMESSAGE" ; then
+                    /usr/bin/echo "MSHW;$DISK;UNKNOWN;Unknown Status";
+                else
+                    /usr/bin/echo "MSHW;$DISK;ALARM;$ERRORMESSAGE";
+                fi
+            fi
+        fi
+    done
 connector:
   displayName: Oracle/Sun Solaris - Sun Disks
   platforms: Oracle/Sun
