MTX-289
align

diff --git a/hdf-to-yaml-converter/src/test/resources/yaml/IBMAIX.yaml b/hdf-to-yaml-converter/src/test/resources/yaml/IBMAIX.yaml
--- a/hdf-to-yaml-converter/src/test/resources/yaml/IBMAIX.yaml
+++ b/hdf-to-yaml-converter/src/test/resources/yaml/IBMAIX.yaml
@@ -1,236 +1,6 @@
 ---
 extends:
 - IBMAIXModels-header
-embedded:
-  EmbeddedFile(1): |-
-    #!/bin/sh
-    for PROC in `/usr/sbin/lsdev -C -c processor -S as -F 'name'`
-        do
-        PROCDETAILS=`/usr/sbin/lsattr -El $PROC -O -a frequency -a type|/usr/bin/grep -v ^#`
-        /usr/bin/echo "MSHW:$PROC:$PROCDETAILS"
-    done
-  EmbeddedFile(3): |-
-    /^ETHERNET STATISTICS/ { if ($3 ~ /(en[0-9].*)/) {nicdevice = $3; gsub("en","ent",nicdevice);gsub(/[\050\051]/,"",nicdevice); nicdevices[nicdevice]=nicdevice}
-                                 else { nicdevice = $3;gsub (/[\050\051]/,"",nicdevice); nicdevices[nicdevice]=nicdevice}
-                             }
-
-    /^Device Type:/ {
-                     if ( ($3 ~ /EtherChannel/ || /Virtual/) || ($0 ~ /Shared Ethernet Adapter/) || ($0 ~ /Link Aggregation/) || ($0 ~ /VLAN/)) { EtherT[nicdevice] = "Logical"; lastLogical = nicdevice }
-                        else { EtherT[nicdevice] = "Physical" }
-                    }
-
-    /^Driver Flags:/ {
-                      nicStatus[nicdevice] = "ALARM";
-                      if ($0 ~ /Running/) { nicStatus[nicdevice] = "OK"; }
-                      else {
-                            getline
-                            if ($0 ~ /Running/) { nicStatus[nicdevice] = "OK";}
-                           }
-                     }
-
-    $1 == "Hardware" && $2 == "Address:" { mac[nicdevice] = $3 ; gsub (/:/,"",mac[nicdevice])}
-
-    # Link
-    /Physical Port Link Stat/ {
-                               if ($NF == "up" || $NF == "Up" || $NF == "UP") {
-                                                                               linkStatus[nicdevice] = "OK";
-                                                                               if ( linkStatus[lastLogical] == "WARN" ) { linkStatus[lastLogical] = "OK" ; nicStatus[lastLogical] = "WARN" ; }
-                                                                              }
-                                  else {
-                                        linkStatus[nicdevice] = "WARN";
-                                        if (linkStatus[lastLogical] == "OK") { nicStatus[lastLogical] = "WARN" }
-                                        if (linkStatus[lastLogical] == "") { linkStatus[lastLogical] = "WARN" ; nicStatus[lastLogical] = "ALARM" }
-                                       }
-                               if ($NF == "Unknown") {linkStatus[nicdevice] = "ALARM";}
-                              }
-
-    $1 == "Link" && $2 == "Status" { if ($4 == "up" || $4 == "Up" || $4 == "UP") { linkStatus[nicdevice] = "OK"; }
-                                          else {linkStatus[nicdevice] = "WARN"; nicStatus[nicdevice] = "OK";}
-                                     }
-
-    $1 == "Link" && $2 == "Status:" { if ($3 == "up" || $3 == "Up" || $3 == "UP") { linkStatus[nicdevice] = "OK";}
-                                           else { linkStatus[nicdevice] = "WARN"; nicStatus[nicdevice] = "OK"; }
-                                      }
-
-    # Speed
-    $0 ~ /Media Speed Running:/ || $0 ~ /Physical Port Speed:/ {
-                                     #linkSpeed[nicdevice] = $4; gsub(/Gbps/,"000",linkSpeed[nicdevice]);gsub(/Mbps/,"",linkSpeed[nicdevice]);
-                                                                     linkSpeed[nicdevice] = $4 $5; gsub(/Gbps/,"000",linkSpeed[nicdevice]);gsub(/Mbps/,"",linkSpeed[nicdevice]);
-                                                                     if ($0 ~ /[Hh]alf [Dd]uplex/) { duplexMode[nicdevice] = "half"; }
-                                        else { duplexMode[nicdevice] = "full"; }
-                                     }
-
-    # Statistics
-    $1 == "Packets:" && $3 == "Packets:" { transmitPackets[nicdevice] = $2; receivePackets[nicdevice] = $4; }
-
-    $1 == "Bytes:" && $3 == "Bytes:" {transmitBytes[nicdevice] = $2;receiveBytes[nicdevice] = $4; }
-
-    $1 == "Transmit" && $2 == "Errors:" && $4 == "Receive" && $5 == "Errors:" { transmitErrors[nicdevice] = $3; receiveErrors[nicdevice] = $6; totalErrors[nicdevice] = transmitErrors[nicdevice] + receiveErrors[nicdevice] ; }
-
-    END { for (nic in nicdevices) {
-              if (EtherT[nic] == "Logical") {
-                 printf("MSHW;%s;%s;%s;%.0f;%.0f;%.0f;%.0f;%.0f;;;%s;;\n", nicdevices[nic],nicStatus[nic],linkStatus[nic],totalErrors[nic],transmitPackets[nic],receivePackets[nic],transmitBytes[nic],receiveBytes[nic],"Logical");
-                 }
-                 else {
-                       printf("MSHW;%s;%s;%s;%.0f;%.0f;%.0f;%.0f;%.0f;%s;%s;%s;%s;\n",nicdevices[nic],nicStatus[nic],linkStatus[nic],totalErrors[nic],transmitPackets[nic],receivePackets[nic],transmitBytes[nic],receiveBytes[nic],linkSpeed[nic],duplexMode[nic],"Physical", mac[nic]);
-                      }
-
-              }
-    }
-  EmbeddedFile(2): |-
-    #!/bin/sh
-    if [ -f /etc/lsattr ]
-        then LSATTR=/etc/lsattr
-        else LSATTR=/usr/sbin/lsattr
-    fi
-    for NIC in `%{SUDO:/usr/sbin/netstat -D}/usr/sbin/netstat -D |awk '/ent_dd/ {print $1} ' |cut -b 7-9`
-    do
-        echo MS_HW_entstat_Start: $NIC
-        /usr/bin/entstat -d en$NIC
-        echo MS_HW_entstat_End: $NIC
-    done
-  EmbeddedFile(5): |-
-    BEGIN {
-        errorCount = 0;
-        lastErrorDescription = "";
-        lastTimestamp = "";
-    }
-    ($5 == "sysplanar0") {
-        errorCount++;
-        lastErrorDescription = $6;
-        for (i=7 ; i<=NF ; i++)
-        {
-            lastErrorDescription = lastErrorDescription " " $i;
-        }
-        lastTimestamp = "20" substr($2, 9, 2) "-" substr($2, 1, 2) "-" substr($2, 3, 2) " " substr($2, 5, 2) ":" substr($2, 7, 2)
-    }
-    END {
-        if (errorCount == 0)
-        {
-            print "MSHW;OK;No error on sysplanar0 as of today";
-        }
-        else if (errorCount == 1)
-        {
-            print "MSHW;ALARM;" lastErrorDescription " on " lastTimestamp;
-        }
-        else
-        {
-            print "MSHW;ALARM;" errorCount " errors in errpt. Last error: " lastErrorDescription " on " lastTimestamp;
-        } # end else
-    }
-  EmbeddedFile(4): |-
-    BEGIN {
-        MemoryObject = 0;
-        DeviceID = "";
-        Size = "";
-        SerialNumber = "";
-        PartNumber = "";
-    }
-    /Memory [DS]IMM:/ {
-        MemoryObject = 1;
-    }
-
-    /Size\.+/ {
-        Size = $0;
-        gsub(" +Size\\.+", "", Size);
-    }
-    /Serial Number\.+/ {
-        SerialNumber = $0;
-        gsub(" +Serial Number\\.+", "", SerialNumber);
-    }
-    /Part Number\.+/ {
-        PartNumber = $0;
-        gsub(" +Part Number\\.+", "", PartNumber);
-    }
-    /Physical Location:/ {
-        if (MemoryObject == 1)
-        {
-            DeviceID = $3;
-
-            if (Size == 0)
-            {
-                Status = "ALARM";
-                StatusInformation = "Failed";
-            }
-            else
-            {
-                Status = "OK";
-                StatusInformation = "";
-            }
-            print "MSHW;" DeviceID ";" Size ";" SerialNumber " - FRU: " PartNumber ";" Status ";" StatusInformation
-        }
-        DeviceID = "";
-        MemoryObject = 0;
-        SerialNumber = "";
-        PartNumber = "";
-    }
-  EmbeddedFile(7): |-
-    /MS_HW_lscfg_Start/ {
-        nicID = "";
-        model = "";
-        MACaddress = "";
-        nicType = "";
-        hwLocationCode = "";
-    }
-    ($1 ~ /^ent[0-9]/) {
-        nicID = $1;
-        hwLocationCode = $2;
-        getline;
-        gsub("^ +", "");
-        model = $0;
-    }
-    /^ *Network Address/ {
-        gsub("^ *Network Address\\.+", "");
-        MACaddress = $1;
-        if (length(MACaddress) == 12)
-        {
-            MACaddress = substr(MACaddress, 1, 2) ":" substr(MACaddress, 3, 2) ":" substr(MACaddress, 5, 2) ":" substr(MACaddress, 7, 2) ":" substr(MACaddress, 9, 2) ":" substr(MACaddress, 11, 2);
-        }
-    }
-    /MS_HW_lscfg_End/ {
-        if (nicID != "")
-        {
-            if (model ~ /Virtual/ || model ~ /EtherChannel/ || model ~ /VLAN/)
-            {
-                nicType = "Logical";
-            }
-            else
-            {
-                nicType = "Physical";
-            }
-            print "MSHW;" nicID ";" model ";" nicType ";" MACaddress ";Location: " hwLocationCode ";"
-        }
-
-        nicID = "";
-        model = "";
-        MACaddress = "";
-        nicType = "";
-        hwLocationCode = "";
-
-    }
-  EmbeddedFile(6): |-
-    #!/bin/sh
-    for NIC in `/usr/sbin/lsdev -C -S a -c adapter -F 'name'|/usr/bin/grep ^ent[0-9]`
-    do
-        echo MS_HW_lscfg_Start: $NIC
-        /usr/sbin/lscfg -v -s -l $NIC 2> /dev/null
-        if [ $? -gt 0 ]; then
-        echo $NIC
-        lsdev -l $NIC |cut -c 17-
-        fi
-        echo MS_HW_lscfg_End: $NIC
-    done
-translations:
-  cpuStatusInformationTranslationTable:
-    stopped: Stopped
-    default: Unknown Status
-    available: Available
-    defined: Defined
-  cpuStatusTranslationTable:
-    stopped: degraded
-    default: UNKNOWN
-    available: ok
-    defined: ok
 connector:
   displayName: IBM AIX - Common
   platforms: IBM POWER
@@ -629,3 +399,233 @@ monitors:
           hw.errors{hw.type="memory"}: $column(4)
         legacyTextParameters:
           StatusInformation: $column(3)
+embedded:
+  EmbeddedFile(1): |-
+    #!/bin/sh
+    for PROC in `/usr/sbin/lsdev -C -c processor -S as -F 'name'`
+        do
+        PROCDETAILS=`/usr/sbin/lsattr -El $PROC -O -a frequency -a type|/usr/bin/grep -v ^#`
+        /usr/bin/echo "MSHW:$PROC:$PROCDETAILS"
+    done
+  EmbeddedFile(3): |-
+    /^ETHERNET STATISTICS/ { if ($3 ~ /(en[0-9].*)/) {nicdevice = $3; gsub("en","ent",nicdevice);gsub(/[\050\051]/,"",nicdevice); nicdevices[nicdevice]=nicdevice}
+                                 else { nicdevice = $3;gsub (/[\050\051]/,"",nicdevice); nicdevices[nicdevice]=nicdevice}
+                             }
+
+    /^Device Type:/ {
+                     if ( ($3 ~ /EtherChannel/ || /Virtual/) || ($0 ~ /Shared Ethernet Adapter/) || ($0 ~ /Link Aggregation/) || ($0 ~ /VLAN/)) { EtherT[nicdevice] = "Logical"; lastLogical = nicdevice }
+                        else { EtherT[nicdevice] = "Physical" }
+                    }
+
+    /^Driver Flags:/ {
+                      nicStatus[nicdevice] = "ALARM";
+                      if ($0 ~ /Running/) { nicStatus[nicdevice] = "OK"; }
+                      else {
+                            getline
+                            if ($0 ~ /Running/) { nicStatus[nicdevice] = "OK";}
+                           }
+                     }
+
+    $1 == "Hardware" && $2 == "Address:" { mac[nicdevice] = $3 ; gsub (/:/,"",mac[nicdevice])}
+
+    # Link
+    /Physical Port Link Stat/ {
+                               if ($NF == "up" || $NF == "Up" || $NF == "UP") {
+                                                                               linkStatus[nicdevice] = "OK";
+                                                                               if ( linkStatus[lastLogical] == "WARN" ) { linkStatus[lastLogical] = "OK" ; nicStatus[lastLogical] = "WARN" ; }
+                                                                              }
+                                  else {
+                                        linkStatus[nicdevice] = "WARN";
+                                        if (linkStatus[lastLogical] == "OK") { nicStatus[lastLogical] = "WARN" }
+                                        if (linkStatus[lastLogical] == "") { linkStatus[lastLogical] = "WARN" ; nicStatus[lastLogical] = "ALARM" }
+                                       }
+                               if ($NF == "Unknown") {linkStatus[nicdevice] = "ALARM";}
+                              }
+
+    $1 == "Link" && $2 == "Status" { if ($4 == "up" || $4 == "Up" || $4 == "UP") { linkStatus[nicdevice] = "OK"; }
+                                          else {linkStatus[nicdevice] = "WARN"; nicStatus[nicdevice] = "OK";}
+                                     }
+
+    $1 == "Link" && $2 == "Status:" { if ($3 == "up" || $3 == "Up" || $3 == "UP") { linkStatus[nicdevice] = "OK";}
+                                           else { linkStatus[nicdevice] = "WARN"; nicStatus[nicdevice] = "OK"; }
+                                      }
+
+    # Speed
+    $0 ~ /Media Speed Running:/ || $0 ~ /Physical Port Speed:/ {
+                                     #linkSpeed[nicdevice] = $4; gsub(/Gbps/,"000",linkSpeed[nicdevice]);gsub(/Mbps/,"",linkSpeed[nicdevice]);
+                                                                     linkSpeed[nicdevice] = $4 $5; gsub(/Gbps/,"000",linkSpeed[nicdevice]);gsub(/Mbps/,"",linkSpeed[nicdevice]);
+                                                                     if ($0 ~ /[Hh]alf [Dd]uplex/) { duplexMode[nicdevice] = "half"; }
+                                        else { duplexMode[nicdevice] = "full"; }
+                                     }
+
+    # Statistics
+    $1 == "Packets:" && $3 == "Packets:" { transmitPackets[nicdevice] = $2; receivePackets[nicdevice] = $4; }
+
+    $1 == "Bytes:" && $3 == "Bytes:" {transmitBytes[nicdevice] = $2;receiveBytes[nicdevice] = $4; }
+
+    $1 == "Transmit" && $2 == "Errors:" && $4 == "Receive" && $5 == "Errors:" { transmitErrors[nicdevice] = $3; receiveErrors[nicdevice] = $6; totalErrors[nicdevice] = transmitErrors[nicdevice] + receiveErrors[nicdevice] ; }
+
+    END { for (nic in nicdevices) {
+              if (EtherT[nic] == "Logical") {
+                 printf("MSHW;%s;%s;%s;%.0f;%.0f;%.0f;%.0f;%.0f;;;%s;;\n", nicdevices[nic],nicStatus[nic],linkStatus[nic],totalErrors[nic],transmitPackets[nic],receivePackets[nic],transmitBytes[nic],receiveBytes[nic],"Logical");
+                 }
+                 else {
+                       printf("MSHW;%s;%s;%s;%.0f;%.0f;%.0f;%.0f;%.0f;%s;%s;%s;%s;\n",nicdevices[nic],nicStatus[nic],linkStatus[nic],totalErrors[nic],transmitPackets[nic],receivePackets[nic],transmitBytes[nic],receiveBytes[nic],linkSpeed[nic],duplexMode[nic],"Physical", mac[nic]);
+                      }
+
+              }
+    }
+  EmbeddedFile(2): |-
+    #!/bin/sh
+    if [ -f /etc/lsattr ]
+        then LSATTR=/etc/lsattr
+        else LSATTR=/usr/sbin/lsattr
+    fi
+    for NIC in `%{SUDO:/usr/sbin/netstat -D}/usr/sbin/netstat -D |awk '/ent_dd/ {print $1} ' |cut -b 7-9`
+    do
+        echo MS_HW_entstat_Start: $NIC
+        /usr/bin/entstat -d en$NIC
+        echo MS_HW_entstat_End: $NIC
+    done
+  EmbeddedFile(5): |-
+    BEGIN {
+        errorCount = 0;
+        lastErrorDescription = "";
+        lastTimestamp = "";
+    }
+    ($5 == "sysplanar0") {
+        errorCount++;
+        lastErrorDescription = $6;
+        for (i=7 ; i<=NF ; i++)
+        {
+            lastErrorDescription = lastErrorDescription " " $i;
+        }
+        lastTimestamp = "20" substr($2, 9, 2) "-" substr($2, 1, 2) "-" substr($2, 3, 2) " " substr($2, 5, 2) ":" substr($2, 7, 2)
+    }
+    END {
+        if (errorCount == 0)
+        {
+            print "MSHW;OK;No error on sysplanar0 as of today";
+        }
+        else if (errorCount == 1)
+        {
+            print "MSHW;ALARM;" lastErrorDescription " on " lastTimestamp;
+        }
+        else
+        {
+            print "MSHW;ALARM;" errorCount " errors in errpt. Last error: " lastErrorDescription " on " lastTimestamp;
+        } # end else
+    }
+  EmbeddedFile(4): |-
+    BEGIN {
+        MemoryObject = 0;
+        DeviceID = "";
+        Size = "";
+        SerialNumber = "";
+        PartNumber = "";
+    }
+    /Memory [DS]IMM:/ {
+        MemoryObject = 1;
+    }
+
+    /Size\.+/ {
+        Size = $0;
+        gsub(" +Size\\.+", "", Size);
+    }
+    /Serial Number\.+/ {
+        SerialNumber = $0;
+        gsub(" +Serial Number\\.+", "", SerialNumber);
+    }
+    /Part Number\.+/ {
+        PartNumber = $0;
+        gsub(" +Part Number\\.+", "", PartNumber);
+    }
+    /Physical Location:/ {
+        if (MemoryObject == 1)
+        {
+            DeviceID = $3;
+
+            if (Size == 0)
+            {
+                Status = "ALARM";
+                StatusInformation = "Failed";
+            }
+            else
+            {
+                Status = "OK";
+                StatusInformation = "";
+            }
+            print "MSHW;" DeviceID ";" Size ";" SerialNumber " - FRU: " PartNumber ";" Status ";" StatusInformation
+        }
+        DeviceID = "";
+        MemoryObject = 0;
+        SerialNumber = "";
+        PartNumber = "";
+    }
+  EmbeddedFile(7): |-
+    /MS_HW_lscfg_Start/ {
+        nicID = "";
+        model = "";
+        MACaddress = "";
+        nicType = "";
+        hwLocationCode = "";
+    }
+    ($1 ~ /^ent[0-9]/) {
+        nicID = $1;
+        hwLocationCode = $2;
+        getline;
+        gsub("^ +", "");
+        model = $0;
+    }
+    /^ *Network Address/ {
+        gsub("^ *Network Address\\.+", "");
+        MACaddress = $1;
+        if (length(MACaddress) == 12)
+        {
+            MACaddress = substr(MACaddress, 1, 2) ":" substr(MACaddress, 3, 2) ":" substr(MACaddress, 5, 2) ":" substr(MACaddress, 7, 2) ":" substr(MACaddress, 9, 2) ":" substr(MACaddress, 11, 2);
+        }
+    }
+    /MS_HW_lscfg_End/ {
+        if (nicID != "")
+        {
+            if (model ~ /Virtual/ || model ~ /EtherChannel/ || model ~ /VLAN/)
+            {
+                nicType = "Logical";
+            }
+            else
+            {
+                nicType = "Physical";
+            }
+            print "MSHW;" nicID ";" model ";" nicType ";" MACaddress ";Location: " hwLocationCode ";"
+        }
+
+        nicID = "";
+        model = "";
+        MACaddress = "";
+        nicType = "";
+        hwLocationCode = "";
+
+    }
+  EmbeddedFile(6): |-
+    #!/bin/sh
+    for NIC in `/usr/sbin/lsdev -C -S a -c adapter -F 'name'|/usr/bin/grep ^ent[0-9]`
+    do
+        echo MS_HW_lscfg_Start: $NIC
+        /usr/sbin/lscfg -v -s -l $NIC 2> /dev/null
+        if [ $? -gt 0 ]; then
+        echo $NIC
+        lsdev -l $NIC |cut -c 17-
+        fi
+        echo MS_HW_lscfg_End: $NIC
+    done
+translations:
+  cpuStatusInformationTranslationTable:
+    stopped: Stopped
+    default: Unknown Status
+    available: Available
+    defined: Defined
+  cpuStatusTranslationTable:
+    stopped: degraded
+    default: UNKNOWN
+    available: ok
+    defined: ok
diff --git a/hdf-to-yaml-converter/src/test/resources/yaml/IBMAIXDisk.yaml b/hdf-to-yaml-converter/src/test/resources/yaml/IBMAIXDisk.yaml
--- a/hdf-to-yaml-converter/src/test/resources/yaml/IBMAIXDisk.yaml
+++ b/hdf-to-yaml-converter/src/test/resources/yaml/IBMAIXDisk.yaml
@@ -1,88 +1,4 @@
 ---
-embedded:
-  EmbeddedFile(1): |-
-    #!/bin/sh
-    for DISK in `/usr/sbin/lsdev -C -c disk -F 'name'`
-    do
-        /usr/sbin/lscfg -vp -l $DISK|/bin/tr "." " "|/usr/bin/awk -v diskId=$DISK 'BEGIN {
-            manufacturer = "";
-            fruNumber = "";
-            serialNumber = "";
-        }
-        /.*/ {
-            if ($1 == "Manufacturer")
-            {
-                manufacturer = $2;
-            }
-
-            if ($1 == "FRU" && $2 == "Number")
-            {
-                fruNumber = $3;
-            }
-
-            if ($1 == "Serial" && $2 == "Number")
-            {
-                serialNumber = $3;
-            }
-        }
-        END {
-            print "MSHW;" diskId ";" manufacturer ";" serialNumber " (FRU: " fruNumber ")"
-        }'
-    done
-  EmbeddedFile(3): |+
-    #!/bin/sh
-    LANG=C
-    export LANG
-
-    ERRORMESSAGE=`%{SUDO:/usr/bin/dd}/usr/bin/dd if=/dev/r$1 of=/dev/null count=20 2>&1`
-    if /usr/bin/test "$?" = "0" ; then
-        STATUS="OK;Working"
-    else
-        STATUS=`/usr/bin/echo $ERRORMESSAGE|/usr/bin/awk -F: '{
-                if ($3 ~ /ermission/)
-                {
-                    print "UNKNOWN;Insufficient privileges"
-                }
-                else if ($3 ~ /o such file/)
-                {
-                    print "UNKNOWN;" $3
-                }
-                else
-                {
-                    print "ALARM;" $3
-                }
-            }'`
-    fi
-    TODAY=`/usr/bin/date +%m%d0000%y`
-    ERRORCOUNT=`/usr/bin/errpt -d H -s $TODAY -N $1|/usr/bin/tail -n +2|/usr/bin/wc -l|/usr/bin/awk '{print $1}'`
-    if /usr/bin/test $ERRORCOUNT -gt 0 ; then
-        LASTERROR=`/usr/bin/errpt -d H -s $TODAY -N $1|/usr/bin/head -n 2|/usr/bin/tail -n 1|/usr/bin/awk '{printf $1 " ("; for (i=6 ; i<NF ; i++) { printf $i " " } print $NF ")"}'`
-    fi
-    /usr/bin/echo "MSHW;$STATUS;$ERRORCOUNT;$LASTERROR"
-    exit
-
-  EmbeddedFile(2): |-
-    #!/bin/sh
-    for DISK in `/usr/sbin/lsdev -C -c disk -F 'name'`
-    do
-        SIZE=`/usr/sbin/lscfg -vp -l $DISK|/usr/bin/awk -F "[() ]" '/hdisk.*[0-9]+ MB)/ { print $(NF-2) }'`
-        /bin/echo "MSHW;$DISK;$SIZE"
-    done
-  EmbeddedFile(4): |-
-    #!/bin/sh
-    LANG=C
-    export LANG
-    TODAY=`/usr/bin/date +%m%d0000%y`
-    ERRORCOUNT=`/usr/bin/errpt -d H -s $TODAY -N $1|/usr/bin/tail -n +2|/usr/bin/wc -l|/usr/bin/awk '{print $1}'`
-    if /usr/bin/test $ERRORCOUNT -gt 0 ; then
-        LASTERROR=`/usr/bin/errpt -d H -s $TODAY -N $1|/usr/bin/head -n 2|/usr/bin/tail -n 1|/usr/bin/awk '{printf $1 " ("; for (i=6 ; i<NF ; i++) { printf $i " " } print $NF ")"}'`
-    fi
-    /usr/bin/echo "MSHW;$ERRORCOUNT;$LASTERROR"
-    exit
-translations:
-  ErrorcounttoStatusTranslationTable:
-    "0": ok
-    default: failed
 connector:
   displayName: IBM AIX - SCSI disks
   platforms: IBM POWER
@@ -296,3 +212,87 @@ monitors:
           hw.status{hw.type="physical_disk"}: $column(1)
         legacyTextParameters:
           StatusInformation: $column(2)
+embedded:
+  EmbeddedFile(1): |-
+    #!/bin/sh
+    for DISK in `/usr/sbin/lsdev -C -c disk -F 'name'`
+    do
+        /usr/sbin/lscfg -vp -l $DISK|/bin/tr "." " "|/usr/bin/awk -v diskId=$DISK 'BEGIN {
+            manufacturer = "";
+            fruNumber = "";
+            serialNumber = "";
+        }
+        /.*/ {
+            if ($1 == "Manufacturer")
+            {
+                manufacturer = $2;
+            }
+
+            if ($1 == "FRU" && $2 == "Number")
+            {
+                fruNumber = $3;
+            }
+
+            if ($1 == "Serial" && $2 == "Number")
+            {
+                serialNumber = $3;
+            }
+        }
+        END {
+            print "MSHW;" diskId ";" manufacturer ";" serialNumber " (FRU: " fruNumber ")"
+        }'
+    done
+  EmbeddedFile(3): |+
+    #!/bin/sh
+    LANG=C
+    export LANG
+
+    ERRORMESSAGE=`%{SUDO:/usr/bin/dd}/usr/bin/dd if=/dev/r$1 of=/dev/null count=20 2>&1`
+    if /usr/bin/test "$?" = "0" ; then
+        STATUS="OK;Working"
+    else
+        STATUS=`/usr/bin/echo $ERRORMESSAGE|/usr/bin/awk -F: '{
+                if ($3 ~ /ermission/)
+                {
+                    print "UNKNOWN;Insufficient privileges"
+                }
+                else if ($3 ~ /o such file/)
+                {
+                    print "UNKNOWN;" $3
+                }
+                else
+                {
+                    print "ALARM;" $3
+                }
+            }'`
+    fi
+    TODAY=`/usr/bin/date +%m%d0000%y`
+    ERRORCOUNT=`/usr/bin/errpt -d H -s $TODAY -N $1|/usr/bin/tail -n +2|/usr/bin/wc -l|/usr/bin/awk '{print $1}'`
+    if /usr/bin/test $ERRORCOUNT -gt 0 ; then
+        LASTERROR=`/usr/bin/errpt -d H -s $TODAY -N $1|/usr/bin/head -n 2|/usr/bin/tail -n 1|/usr/bin/awk '{printf $1 " ("; for (i=6 ; i<NF ; i++) { printf $i " " } print $NF ")"}'`
+    fi
+    /usr/bin/echo "MSHW;$STATUS;$ERRORCOUNT;$LASTERROR"
+    exit
+
+  EmbeddedFile(2): |-
+    #!/bin/sh
+    for DISK in `/usr/sbin/lsdev -C -c disk -F 'name'`
+    do
+        SIZE=`/usr/sbin/lscfg -vp -l $DISK|/usr/bin/awk -F "[() ]" '/hdisk.*[0-9]+ MB)/ { print $(NF-2) }'`
+        /bin/echo "MSHW;$DISK;$SIZE"
+    done
+  EmbeddedFile(4): |-
+    #!/bin/sh
+    LANG=C
+    export LANG
+    TODAY=`/usr/bin/date +%m%d0000%y`
+    ERRORCOUNT=`/usr/bin/errpt -d H -s $TODAY -N $1|/usr/bin/tail -n +2|/usr/bin/wc -l|/usr/bin/awk '{print $1}'`
+    if /usr/bin/test $ERRORCOUNT -gt 0 ; then
+        LASTERROR=`/usr/bin/errpt -d H -s $TODAY -N $1|/usr/bin/head -n 2|/usr/bin/tail -n 1|/usr/bin/awk '{printf $1 " ("; for (i=6 ; i<NF ; i++) { printf $i " " } print $NF ")"}'`
+    fi
+    /usr/bin/echo "MSHW;$ERRORCOUNT;$LASTERROR"
+    exit
+translations:
+  ErrorcounttoStatusTranslationTable:
+    "0": ok
+    default: failed
